#!/data/data/com.termux/files/usr/bin/env bash

cd $HOME
clear

set -u

# proot-distro install
pkg i -y root-repo x11-repo
pkg i -y proot-distro

bin="$HOME/.local/bin"

# directories for cache and wpd
mkdir "$bin"
mkdir $HOME/.cache/

# wpd install
curl -o $bin/wpd https://raw.githubusercontent.com/Welpyes/wide-proot-distro/refs/heads/master/wpd
chmod +x $bin/wpd

clear 

echo "installation complete to invoke it type wpd"
